default_platform(:android)

platform :android do

  desc "build"
  lane :build do
    gradle(
        task: 'assembleRelease',
        flavor: 'google',
        properties: {
                 "android.injected.signing.store.file" => "/Users/joaquimcardeira/pems/keystore",
                 "android.injected.signing.store.password" => "password",
                 "android.injected.signing.key.alias" => "key0",
                 "android.injected.signing.key.password" => "password"
               }
    )
  end
end